/*
 * DO NOT EDIT!!! DO NOT EDIT!!! DO NOT EDIT!!!
 * 
 * Generated by the TSN.1 Compiler v6.2.16 (Evaluation Edition) - 
 * Protomatics, Inc.
 * 
 * Visit http://www.protomatics.com for more information.
 */

#ifndef ZNP_H
#define ZNP_H


#include "config.h"
#include <epan/packet.h>
#include <epan/except.h>



typedef enum
{
   AF_DATA_REQUEST_SREQ = 9217,
   AF_DATA_REQUEST_SRSP = 25601,
   AF_DATA_REQUEST_EXT_SREQ = 9218,
   AF_DATA_REQUEST_EXT_SRSP = 25602,
   AF_DATA_CONFIRM_AREQ = 17536,
   AF_INCOMING_MSG_AREQ = 17537,
   ZDO_MGMT_PERMIT_JOIN_REQ_SREQ = 9526,
   ZDO_MGMT_PERMIT_JOIN_REQ_SRSP = 25910,
   ZDO_MGMT_PERMIT_JOIN_RSP_AREQ = 17846 
} ZnpCpmmandType;

extern const value_string ZnpCpmmandType_value_string_table[];

typedef enum
{
   AF_ACK_REQUEST = 16,
   AF_DISCV_ROUTE = 32,
   AF_EN_SECURITY = 64 
} OptionsType;

extern const value_string OptionsType_value_string_table[];

typedef enum
{
   SUCCESS = 0,
   FAILURE = 1 
} StatusType;

extern const value_string StatusType_value_string_table[];

typedef struct __AFDataReqSreq__
{

   /* Fields */
   guint16      DestnationAddress;
   guint8       DestnationEndPoint;
   guint8       SourceEndPoint;
   guint16      ClusterId;
   guint8       TransId;
   OptionsType  Options;
   guint8       Radius;
   guint8       Len;
   guint8       *Data;
} AFDataReqSreq;

extern void AFDataReqSreq_register(int proto_index);

extern guint32 AFDataReqSreq_dissect
   (
      AFDataReqSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFDataReqSreq_dissect
   (
      AFDataReqSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __AFDataReqSrsp__
{

   /* Fields */
   StatusType   Status;
} AFDataReqSrsp;

extern void AFDataReqSrsp_register(int proto_index);

extern guint32 AFDataReqSrsp_dissect
   (
      AFDataReqSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFDataReqSrsp_dissect
   (
      AFDataReqSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __AFDataReqExtSreq__
{

   /* Fields */
   guint8       DestnationAddressMode;
   guint64      DestnationAddress;
   guint8       DestnationEndPoint;
   guint16      PanId;
   guint8       SourceEndPoint;
   guint16      ClusterId;
   guint8       TransId;
   OptionsType  Options;
   guint8       Radius;
   guint16      Len;
   guint8       *Data;
} AFDataReqExtSreq;

extern void AFDataReqExtSreq_register(int proto_index);

extern guint32 AFDataReqExtSreq_dissect
   (
      AFDataReqExtSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFDataReqExtSreq_dissect
   (
      AFDataReqExtSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __AFDataReqExtSrsp__
{

   /* Fields */
   StatusType   Status;
} AFDataReqExtSrsp;

extern void AFDataReqExtSrsp_register(int proto_index);

extern guint32 AFDataReqExtSrsp_dissect
   (
      AFDataReqExtSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFDataReqExtSrsp_dissect
   (
      AFDataReqExtSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __AFDataConfirmAreq__
{

   /* Fields */
   StatusType   Status;
   guint8       EndPoint;
   guint8       TransId;
} AFDataConfirmAreq;

extern void AFDataConfirmAreq_register(int proto_index);

extern guint32 AFDataConfirmAreq_dissect
   (
      AFDataConfirmAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFDataConfirmAreq_dissect
   (
      AFDataConfirmAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __AFIncomingMsgAreq__
{

   /* Fields */
   guint16      GroupId;
   guint16      ClusterId;
   guint16      SourceAddress;
   guint8       SourceEndpoint;
   guint8       DestnationEndPoint;
   guint8       WasBroadcast;
   guint8       LinkQuality;
   guint8       SecurityUse;
   guint32      TimeStamp;
   guint8       TransSequenceNumber;
   guint8       Len;
   guint8       *Data;
   guint16      MacSourceAddress;
   guint8       MessageResultRadius;
} AFIncomingMsgAreq;

extern void AFIncomingMsgAreq_register(int proto_index);

extern guint32 AFIncomingMsgAreq_dissect
   (
      AFIncomingMsgAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _AFIncomingMsgAreq_dissect
   (
      AFIncomingMsgAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __ZDOMgmtPermitJoinReqSreq__
{

   /* Fields */
   guint16      DestnationAddress;
   guint8       Duration;
   guint8       TCSignificance;
} ZDOMgmtPermitJoinReqSreq;

extern void ZDOMgmtPermitJoinReqSreq_register(int proto_index);

extern guint32 ZDOMgmtPermitJoinReqSreq_dissect
   (
      ZDOMgmtPermitJoinReqSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _ZDOMgmtPermitJoinReqSreq_dissect
   (
      ZDOMgmtPermitJoinReqSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __ZDOMgmtPermitJoinReqSrsp__
{

   /* Fields */
   StatusType   Status;
} ZDOMgmtPermitJoinReqSrsp;

extern void ZDOMgmtPermitJoinReqSrsp_register(int proto_index);

extern guint32 ZDOMgmtPermitJoinReqSrsp_dissect
   (
      ZDOMgmtPermitJoinReqSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _ZDOMgmtPermitJoinReqSrsp_dissect
   (
      ZDOMgmtPermitJoinReqSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __ZDOMgmtPermitJoinRspAreq__
{

   /* Fields */
   guint16      SourceAddress;
   StatusType   Status;
} ZDOMgmtPermitJoinRspAreq;

extern void ZDOMgmtPermitJoinRspAreq_register(int proto_index);

extern guint32 ZDOMgmtPermitJoinRspAreq_dissect
   (
      ZDOMgmtPermitJoinRspAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _ZDOMgmtPermitJoinRspAreq_dissect
   (
      ZDOMgmtPermitJoinRspAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );

typedef struct __ZnpPacket__
{

   /* Fields */
   guint8       StartBytes;
   ZnpCpmmandType  CmdType;

   union
   {
      AFDataReqSreq  *afDataReqSreq;
      AFDataReqSrsp  *afDataReqSrsp;
      AFDataReqExtSreq  *afDataReqExtSreq;
      AFDataReqExtSrsp  *afDataReqExtSrsp;
      AFDataConfirmAreq  *adDataConfirmAreq;
      AFIncomingMsgAreq  *afIncomingMsgAreq;
      ZDOMgmtPermitJoinReqSreq  *zdoMgmtPermitJoinReqSreq;
      ZDOMgmtPermitJoinReqSrsp  *zdoMgmtPermitJoinReqSrsp;
      ZDOMgmtPermitJoinRspAreq  *zdoMgmtPermitJoinRspAreq;
   } Payload;

} ZnpPacket;

extern void ZnpPacket_register(int proto_index);

extern guint32 ZnpPacket_dissect
   (
      ZnpPacket *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   );

extern guint32 _ZnpPacket_dissect
   (
      ZnpPacket *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   );


#endif
