/*
 * DO NOT EDIT!!! DO NOT EDIT!!! DO NOT EDIT!!!
 * 
 * Generated by the TSN.1 Compiler v6.2.16 (Evaluation Edition) - 
 * Protomatics, Inc.
 * 
 * Visit http://www.protomatics.com for more information.
 */

#include "znp.h"
#include <epan/tvbuff.h>
#include <epan/to_str.h>
#include <epan/addr_resolv.h>
#include <string.h>
#include <stdio.h>

#define MAX_TSN1_MSG_FIELD_NAME_LEN  128

#define signext8(v, n) \
((n) == 8 || ((v) & (1 << ((n) - 1))) == 0 ? \
(gint8) (v) : (gint8) ((0xFF >> (n) << (n)) | (v)))

#define signext16(v, n) \
((n) == 16 || ((v) & (1 << ((n) - 1))) == 0 ? \
(gint16) (v) : (gint16) ((0xFFFF >> (n) << (n)) | (v)))

#define signext32(v, n) \
((n) == 32 || ((v) & (1 << ((n) - 1))) == 0 ? \
(gint32) (v) : (gint32) ((0xFFFFFFFF >> (n) << (n)) | (v)))

#define signext64(v, n) \
((n) == 64 || ((v) & (G_GINT64_CONSTANT(1) << ((n) - 1))) == 0 ? \
(gint64) (v) : (gint64) ((G_GINT64_CONSTANT(0xFFFFFFFFFFFFFFFFU) >> (n) << (n)) | (v)))

#define pack8(buf, offset, value, nbit) \
do \
{ \
   guint32 _n = (offset) >> 3; \
   guint32 _r = (offset) & 0x7; \
   guint32 _l = _r + (nbit); \
    \
   (buf)[_n] = ((buf)[_n] >> (8 - _r) << (8 - _r)) | \
   ((((value) << (8 - (nbit))) & 0xFF) >> _r); \
    \
   if(_l > 8) \
   { \
      (buf)[_n + 1] = (value) << (16 - _l); \
   } \
} while(0)

#define unpack8(value, buf, offset, nbit) \
{ \
      guint32 _n  = (offset) >> 3; \
      guint32 _r  = (offset) & 0x7; \
      guint32 _r2 = 8 - _r; \
      guint32 _v  = (guint32) (((buf)[_n] << _r) & 0xff); \
      guint32 _v2 = 0; \
    \
      if(_r2 < (nbit)) \
      { \
         _v2 = (guint32) ((buf)[_n + 1] >> _r2); \
      } \
    \
      (value) = ((_v | _v2) >> (8 - (nbit))); \
}

/* Wireshark tvb_get_bitsXXX functions are incomplete. */
/* Use our own versions for now. */
#define tvb_get_bits16(tvb, offset, nbit, enc) ((guint16) (((enc) & ENC_LITTLE_ENDIAN) ? _tvb_get_bits32_le_(tvb, offset, nbit) : _tvb_get_bits32_(tvb, offset, nbit)))
#define tvb_get_bits32(tvb, offset, nbit, enc) (((enc) & ENC_LITTLE_ENDIAN) ? _tvb_get_bits32_le_(tvb, offset, nbit) : _tvb_get_bits32_(tvb, offset, nbit))
#define tvb_get_bits64(tvb, offset, nbit, enc) (((enc) & ENC_LITTLE_ENDIAN) ? _tvb_get_bits64_le_(tvb, offset, nbit) : _tvb_get_bits64_(tvb, offset, nbit))

#ifdef __GNUC__
#define ATTR_UNUSED __attribute__((unused))
#else
#define ATTR_UNUSED
#endif
static guint8 tvb_get_bits8_le
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   ) ATTR_UNUSED;

static guint32 _tvb_get_bits32_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   ) ATTR_UNUSED;

static guint32 _tvb_get_bits32_le_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   ) ATTR_UNUSED;

static guint64 _tvb_get_bits64_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   ) ATTR_UNUSED;

static guint64 _tvb_get_bits64_le_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   ) ATTR_UNUSED;

static void tvb_get_bits_buf_be
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit,
      guint8   *vbuf,
      guint32   voffset
   ) ATTR_UNUSED;

static void tvb_get_bits_buf_le
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit,
      guint8   *vbuf,
      guint32   voffset
   ) ATTR_UNUSED;

static guint32 tvb_count1s
   (
      guint32 value,
      guint32 nbit
   ) ATTR_UNUSED;

static guint32 tvb_count1s_64
   (
      guint64 value,
      guint32 nbit
   ) ATTR_UNUSED;

static guint32 tvb_count1s_buf
   (
      const guint8 *buf,
      guint32       offset,
      guint32       nbit
   ) ATTR_UNUSED;

static guint8 tvb_get_bits8_le
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   )
{
      guint32 n = offset >> 3;
      guint32 r = offset & 0x7;
      guint32 l = r + nbit;
      guint32 v = (tvb_get_guint8(tvb, n) >> r) & (0xFF >> (8 - nbit));

      if(l > 8)
      {
         v |= (tvb_get_guint8(tvb, n + 1) & (0xFF >> (16 - l))) << (8 - r);
      }

      return (guint8) v;
}

static guint32 _tvb_get_bits32_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   )
{
      guint32 value = 0;
      guint32 value2;

      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         value2 = tvb_get_bits8(tvb, offset, 8);
         value  = (value << 8) | value2;
      }

      if(nbit != 0)
      {
         value2 = tvb_get_bits8(tvb, offset, nbit);
         value  = (value << nbit) | value2;
      }

      return value;
}

static guint32 _tvb_get_bits32_le_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   )
{
      guint32 nbit2 = nbit;
      guint32 value = 0;
      guint32 value2;

      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         value2 = tvb_get_bits8_le(tvb, offset, 8);
         value |= value2 << (nbit2 - nbit);
      }

      if(nbit != 0)
      {
         value2 = tvb_get_bits8_le(tvb, offset, nbit);
         value |= value2 << (nbit2 - nbit);
      }

      return value;
}

static guint64 _tvb_get_bits64_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   )
{
      guint64 value = 0;
      guint64 value2;

      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         value2 = tvb_get_bits8(tvb, offset, 8);
         value  = (value << 8) | value2;
      }

      if(nbit != 0)
      {
         value2 = tvb_get_bits8(tvb, offset, nbit);
         value  = (value << nbit) | value2;
      }

      return value;
}

static guint64 _tvb_get_bits64_le_
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit
   )
{
      guint32 nbit2 = nbit;
      guint64 value = 0;
      guint64 value2;

      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         value2 = tvb_get_bits8_le(tvb, offset, 8);
         value |= value2 << (nbit2 - nbit);
      }

      if(nbit != 0)
      {
         value2 = tvb_get_bits8_le(tvb, offset, nbit);
         value |= value2 << (nbit2 - nbit);
      }

      return value;
}

static void tvb_get_bits_buf_be
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit,
      guint8   *vbuf,
      guint32   voffset
   )
{
      for(; nbit > 8; nbit -= 8, offset += 8, voffset += 8)
      {
         pack8(vbuf, voffset, tvb_get_bits8(tvb, offset, 8), 8);
      }

      pack8(vbuf, voffset, tvb_get_bits8(tvb, offset, nbit), nbit);
}

static void tvb_get_bits_buf_le
   (
      tvbuff_t *tvb,
      guint32   offset,
      guint32   nbit,
      guint8   *vbuf,
      guint32   voffset
   )
{
      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         pack8(vbuf, voffset + nbit - 8, tvb_get_bits8_le(tvb, offset, 8), 8);
      }

      pack8(vbuf, voffset, tvb_get_bits8_le(tvb, offset, nbit), nbit);
}

static guint32 tvb_count1s
   (
      guint32 value,
      guint32 nbit
   )
{
      guint32 n = 0;
      guint32 i = 0;

      for(i = 0; i < nbit; ++i)
      {
         if((value >> i) & 0x1)
         {
            ++n;
         }
      }

      return n;
}

static guint32 tvb_count1s_64
   (
      guint64 value,
      guint32 nbit
   )
{
      guint32 n = 0;
      guint32 i = 0;

      for(i = 0; i < nbit; ++i)
      {
         if((value >> i) & 0x1)
         {
            ++n;
         }
      }

      return n;
}

static guint32 tvb_count1s_buf
   (
      const guint8 *buf,
      guint32       offset,
      guint32       nbit
   )
{
      guint32 n = 0;
      guint32 value;

      for(; nbit > 8; nbit -= 8, offset += 8)
      {
         unpack8(value, buf, offset, 8);
         n += tvb_count1s(value, 8);
      }

      unpack8(value, buf, offset, nbit);
      n += tvb_count1s(value, nbit);

      return n;
}



const value_string ZnpCpmmandType_value_string_table[] =
{
   {9217, "AF_DATA_REQUEST_SREQ"},
   {25601, "AF_DATA_REQUEST_SRSP"},
   {9218, "AF_DATA_REQUEST_EXT_SREQ"},
   {25602, "AF_DATA_REQUEST_EXT_SRSP"},
   {17536, "AF_DATA_CONFIRM_AREQ"},
   {17537, "AF_INCOMING_MSG_AREQ"},
   {9526, "ZDO_MGMT_PERMIT_JOIN_REQ_SREQ"},
   {25910, "ZDO_MGMT_PERMIT_JOIN_REQ_SRSP"},
   {17846, "ZDO_MGMT_PERMIT_JOIN_RSP_AREQ"},
   {0, NULL}
};

const value_string OptionsType_value_string_table[] =
{
   {16, "AF_ACK_REQUEST"},
   {32, "AF_DISCV_ROUTE"},
   {64, "AF_EN_SECURITY"},
   {0, NULL}
};

const value_string StatusType_value_string_table[] =
{
   {0, "SUCCESS"},
   {1, "FAILURE"},
   {0, NULL}
};

gint AFDataReqSreq_msg_index = -1;

static hf_register_info AFDataReqSreq_msg_info[] =
{
   {
      &AFDataReqSreq_msg_index,
      {
         "AFDataReqSreq",
         "AFDataReqSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int AFDataReqSreq_DestnationAddress_field_index = -1;

static hf_register_info AFDataReqSreq_DestnationAddress_field_info[] =
{
   {
      &AFDataReqSreq_DestnationAddress_field_index,
      {
         "DestnationAddress",
         "AFDataReqSreq.DestnationAddress",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationAddress",
         HFILL
      }
   }
};


static int AFDataReqSreq_DestnationEndPoint_field_index = -1;

static hf_register_info AFDataReqSreq_DestnationEndPoint_field_info[] =
{
   {
      &AFDataReqSreq_DestnationEndPoint_field_index,
      {
         "DestnationEndPoint",
         "AFDataReqSreq.DestnationEndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationEndPoint",
         HFILL
      }
   }
};


static int AFDataReqSreq_SourceEndPoint_field_index = -1;

static hf_register_info AFDataReqSreq_SourceEndPoint_field_info[] =
{
   {
      &AFDataReqSreq_SourceEndPoint_field_index,
      {
         "SourceEndPoint",
         "AFDataReqSreq.SourceEndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "SourceEndPoint",
         HFILL
      }
   }
};


static int AFDataReqSreq_ClusterId_field_index = -1;

static hf_register_info AFDataReqSreq_ClusterId_field_info[] =
{
   {
      &AFDataReqSreq_ClusterId_field_index,
      {
         "ClusterId",
         "AFDataReqSreq.ClusterId",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "ClusterId",
         HFILL
      }
   }
};


static int AFDataReqSreq_TransId_field_index = -1;

static hf_register_info AFDataReqSreq_TransId_field_info[] =
{
   {
      &AFDataReqSreq_TransId_field_index,
      {
         "TransId",
         "AFDataReqSreq.TransId",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "TransId",
         HFILL
      }
   }
};


extern const value_string OptionsType_value_string_table[];
static int AFDataReqSreq_Options_field_index = -1;

static hf_register_info AFDataReqSreq_Options_field_info[] =
{
   {
      &AFDataReqSreq_Options_field_index,
      {
         "Options",
         "AFDataReqSreq.Options",
         FT_UINT8,
         BASE_DEC,
         VALS(OptionsType_value_string_table),
         0x0,
         "Options",
         HFILL
      }
   }
};


static int AFDataReqSreq_Radius_field_index = -1;

static hf_register_info AFDataReqSreq_Radius_field_info[] =
{
   {
      &AFDataReqSreq_Radius_field_index,
      {
         "Radius",
         "AFDataReqSreq.Radius",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "Radius",
         HFILL
      }
   }
};


static int AFDataReqSreq_Len_field_index = -1;

static hf_register_info AFDataReqSreq_Len_field_info[] =
{
   {
      &AFDataReqSreq_Len_field_index,
      {
         "Len",
         "AFDataReqSreq.Len",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "Len",
         HFILL
      }
   }
};


static int AFDataReqSreq_Data_field_index = -1;

static hf_register_info AFDataReqSreq_Data_field_info[] =
{
   {
      &AFDataReqSreq_Data_field_index,
      {
         "Data",
         "AFDataReqSreq.Data",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "Data",
         HFILL
      }
   }
};



gint AFDataReqSreq_tree_index = -1;

static gint *AFDataReqSreq_tree_table[] =
{
   &AFDataReqSreq_tree_index
};

void AFDataReqSreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_msg_info,
         array_length(AFDataReqSreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_DestnationAddress_field_info,
         array_length(AFDataReqSreq_DestnationAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_DestnationEndPoint_field_info,
         array_length(AFDataReqSreq_DestnationEndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_SourceEndPoint_field_info,
         array_length(AFDataReqSreq_SourceEndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_ClusterId_field_info,
         array_length(AFDataReqSreq_ClusterId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_TransId_field_info,
         array_length(AFDataReqSreq_TransId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_Options_field_info,
         array_length(AFDataReqSreq_Options_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_Radius_field_info,
         array_length(AFDataReqSreq_Radius_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_Len_field_info,
         array_length(AFDataReqSreq_Len_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSreq_Data_field_info,
         array_length(AFDataReqSreq_Data_field_info)
      );

   proto_register_subtree_array
      (
         AFDataReqSreq_tree_table,
         array_length(AFDataReqSreq_tree_table)
      );
}

guint32 AFDataReqSreq_dissect
   (
      AFDataReqSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFDataReqSreq_dissect
      (
         msg,
         NULL,
         AFDataReqSreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFDataReqSreq_dissect
   (
      AFDataReqSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFDataReqSreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFDataReqSreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFDataReqSreq_tree_index);
   }
   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationAddress = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_DestnationAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationEndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_DestnationEndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationEndPoint
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SourceEndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_SourceEndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SourceEndPoint
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->ClusterId = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_ClusterId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->ClusterId
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TransId = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_TransId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TransId
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Options;

      guint8_Options = tvb_get_bits8(tvb, offset, nbit);

      msg->Options = (OptionsType) guint8_Options;

      proto_tree_add_uint
         (
            tree,
            AFDataReqSreq_Options_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Options
         );
   }
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Radius = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_Radius_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Radius
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Len = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqSreq_Len_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Len
      );
   offset += nbit;

   nbit = ((guint32) ((8) * (msg->Len)));
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   if(nbit != 0)
   {
      nbyte = (nbit + 7) >> 3;
      msg->Data = (guint8 *) wmem_alloc(wmem_packet_scope(), nbyte);
      DISSECTOR_ASSERT(!(msg->Data == NULL));
      memset(msg->Data, 0, nbyte);
      tvb_get_bits_buf_be(tvb, offset, nbit, msg->Data, 0);

      {
         char *text = (char *) wmem_alloc(wmem_packet_scope(), nbyte * 2 + 3);
         char *p = text;
         guint32 j;

         DISSECTOR_ASSERT(text != NULL);
         *p++ = '0';
         *p++ = 'x';
         for(j = 0; j < nbyte; ++j)
         {
            p += sprintf(p, "%02x", msg->Data[j]);
         }
         *p = '\0';

         proto_tree_add_none_format
            (
               tree,
               AFDataReqSreq_Data_field_index,
               tvb,
               offset >> 3,
               ((offset & 0x7) + nbit + 7) >> 3,
               "%s: %s",
               "Data",
               text
            );
      }
      offset += nbit;
   }

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint AFDataReqSrsp_msg_index = -1;

static hf_register_info AFDataReqSrsp_msg_info[] =
{
   {
      &AFDataReqSrsp_msg_index,
      {
         "AFDataReqSrsp",
         "AFDataReqSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

extern const value_string StatusType_value_string_table[];
static int AFDataReqSrsp_Status_field_index = -1;

static hf_register_info AFDataReqSrsp_Status_field_info[] =
{
   {
      &AFDataReqSrsp_Status_field_index,
      {
         "Status",
         "AFDataReqSrsp.Status",
         FT_UINT8,
         BASE_DEC,
         VALS(StatusType_value_string_table),
         0x0,
         "Status",
         HFILL
      }
   }
};



gint AFDataReqSrsp_tree_index = -1;

static gint *AFDataReqSrsp_tree_table[] =
{
   &AFDataReqSrsp_tree_index
};

void AFDataReqSrsp_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFDataReqSrsp_msg_info,
         array_length(AFDataReqSrsp_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqSrsp_Status_field_info,
         array_length(AFDataReqSrsp_Status_field_info)
      );

   proto_register_subtree_array
      (
         AFDataReqSrsp_tree_table,
         array_length(AFDataReqSrsp_tree_table)
      );
}

guint32 AFDataReqSrsp_dissect
   (
      AFDataReqSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFDataReqSrsp_dissect
      (
         msg,
         NULL,
         AFDataReqSrsp_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFDataReqSrsp_dissect
   (
      AFDataReqSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFDataReqSrsp"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFDataReqSrsp"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFDataReqSrsp_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Status;

      guint8_Status = tvb_get_bits8(tvb, offset, nbit);

      msg->Status = (StatusType) guint8_Status;

      proto_tree_add_uint
         (
            tree,
            AFDataReqSrsp_Status_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Status
         );
   }
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint AFDataReqExtSreq_msg_index = -1;

static hf_register_info AFDataReqExtSreq_msg_info[] =
{
   {
      &AFDataReqExtSreq_msg_index,
      {
         "AFDataReqExtSreq",
         "AFDataReqExtSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int AFDataReqExtSreq_DestnationAddressMode_field_index = -1;

static hf_register_info AFDataReqExtSreq_DestnationAddressMode_field_info[] =
{
   {
      &AFDataReqExtSreq_DestnationAddressMode_field_index,
      {
         "DestnationAddressMode",
         "AFDataReqExtSreq.DestnationAddressMode",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationAddressMode",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_DestnationAddress_field_index = -1;

static hf_register_info AFDataReqExtSreq_DestnationAddress_field_info[] =
{
   {
      &AFDataReqExtSreq_DestnationAddress_field_index,
      {
         "DestnationAddress",
         "AFDataReqExtSreq.DestnationAddress",
         FT_UINT64,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationAddress",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_DestnationEndPoint_field_index = -1;

static hf_register_info AFDataReqExtSreq_DestnationEndPoint_field_info[] =
{
   {
      &AFDataReqExtSreq_DestnationEndPoint_field_index,
      {
         "DestnationEndPoint",
         "AFDataReqExtSreq.DestnationEndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationEndPoint",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_PanId_field_index = -1;

static hf_register_info AFDataReqExtSreq_PanId_field_info[] =
{
   {
      &AFDataReqExtSreq_PanId_field_index,
      {
         "PanId",
         "AFDataReqExtSreq.PanId",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "PanId",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_SourceEndPoint_field_index = -1;

static hf_register_info AFDataReqExtSreq_SourceEndPoint_field_info[] =
{
   {
      &AFDataReqExtSreq_SourceEndPoint_field_index,
      {
         "SourceEndPoint",
         "AFDataReqExtSreq.SourceEndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "SourceEndPoint",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_ClusterId_field_index = -1;

static hf_register_info AFDataReqExtSreq_ClusterId_field_info[] =
{
   {
      &AFDataReqExtSreq_ClusterId_field_index,
      {
         "ClusterId",
         "AFDataReqExtSreq.ClusterId",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "ClusterId",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_TransId_field_index = -1;

static hf_register_info AFDataReqExtSreq_TransId_field_info[] =
{
   {
      &AFDataReqExtSreq_TransId_field_index,
      {
         "TransId",
         "AFDataReqExtSreq.TransId",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "TransId",
         HFILL
      }
   }
};


extern const value_string OptionsType_value_string_table[];
static int AFDataReqExtSreq_Options_field_index = -1;

static hf_register_info AFDataReqExtSreq_Options_field_info[] =
{
   {
      &AFDataReqExtSreq_Options_field_index,
      {
         "Options",
         "AFDataReqExtSreq.Options",
         FT_UINT8,
         BASE_DEC,
         VALS(OptionsType_value_string_table),
         0x0,
         "Options",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_Radius_field_index = -1;

static hf_register_info AFDataReqExtSreq_Radius_field_info[] =
{
   {
      &AFDataReqExtSreq_Radius_field_index,
      {
         "Radius",
         "AFDataReqExtSreq.Radius",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "Radius",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_Len_field_index = -1;

static hf_register_info AFDataReqExtSreq_Len_field_info[] =
{
   {
      &AFDataReqExtSreq_Len_field_index,
      {
         "Len",
         "AFDataReqExtSreq.Len",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "Len",
         HFILL
      }
   }
};


static int AFDataReqExtSreq_Data_field_index = -1;

static hf_register_info AFDataReqExtSreq_Data_field_info[] =
{
   {
      &AFDataReqExtSreq_Data_field_index,
      {
         "Data",
         "AFDataReqExtSreq.Data",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "Data",
         HFILL
      }
   }
};



gint AFDataReqExtSreq_tree_index = -1;

static gint *AFDataReqExtSreq_tree_table[] =
{
   &AFDataReqExtSreq_tree_index
};

void AFDataReqExtSreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_msg_info,
         array_length(AFDataReqExtSreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_DestnationAddressMode_field_info,
         array_length(AFDataReqExtSreq_DestnationAddressMode_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_DestnationAddress_field_info,
         array_length(AFDataReqExtSreq_DestnationAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_DestnationEndPoint_field_info,
         array_length(AFDataReqExtSreq_DestnationEndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_PanId_field_info,
         array_length(AFDataReqExtSreq_PanId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_SourceEndPoint_field_info,
         array_length(AFDataReqExtSreq_SourceEndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_ClusterId_field_info,
         array_length(AFDataReqExtSreq_ClusterId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_TransId_field_info,
         array_length(AFDataReqExtSreq_TransId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_Options_field_info,
         array_length(AFDataReqExtSreq_Options_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_Radius_field_info,
         array_length(AFDataReqExtSreq_Radius_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_Len_field_info,
         array_length(AFDataReqExtSreq_Len_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSreq_Data_field_info,
         array_length(AFDataReqExtSreq_Data_field_info)
      );

   proto_register_subtree_array
      (
         AFDataReqExtSreq_tree_table,
         array_length(AFDataReqExtSreq_tree_table)
      );
}

guint32 AFDataReqExtSreq_dissect
   (
      AFDataReqExtSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFDataReqExtSreq_dissect
      (
         msg,
         NULL,
         AFDataReqExtSreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFDataReqExtSreq_dissect
   (
      AFDataReqExtSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFDataReqExtSreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFDataReqExtSreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFDataReqExtSreq_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationAddressMode = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_DestnationAddressMode_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationAddressMode
      );
   offset += nbit;

   nbit = 64;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationAddress = tvb_get_bits64(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint64
      (
         tree,
         AFDataReqExtSreq_DestnationAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationEndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_DestnationEndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationEndPoint
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->PanId = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_PanId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->PanId
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SourceEndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_SourceEndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SourceEndPoint
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->ClusterId = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_ClusterId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->ClusterId
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TransId = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_TransId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TransId
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Options;

      guint8_Options = tvb_get_bits8(tvb, offset, nbit);

      msg->Options = (OptionsType) guint8_Options;

      proto_tree_add_uint
         (
            tree,
            AFDataReqExtSreq_Options_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Options
         );
   }
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Radius = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_Radius_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Radius
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Len = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFDataReqExtSreq_Len_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Len
      );
   offset += nbit;

   nbit = ((guint32) ((8) * (msg->Len)));
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   if(nbit != 0)
   {
      nbyte = (nbit + 7) >> 3;
      msg->Data = (guint8 *) wmem_alloc(wmem_packet_scope(), nbyte);
      DISSECTOR_ASSERT(!(msg->Data == NULL));
      memset(msg->Data, 0, nbyte);
      tvb_get_bits_buf_be(tvb, offset, nbit, msg->Data, 0);

      {
         char *text = (char *) wmem_alloc(wmem_packet_scope(), nbyte * 2 + 3);
         char *p = text;
         guint32 j;

         DISSECTOR_ASSERT(text != NULL);
         *p++ = '0';
         *p++ = 'x';
         for(j = 0; j < nbyte; ++j)
         {
            p += sprintf(p, "%02x", msg->Data[j]);
         }
         *p = '\0';

         proto_tree_add_none_format
            (
               tree,
               AFDataReqExtSreq_Data_field_index,
               tvb,
               offset >> 3,
               ((offset & 0x7) + nbit + 7) >> 3,
               "%s: %s",
               "Data",
               text
            );
      }
      offset += nbit;
   }

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint AFDataReqExtSrsp_msg_index = -1;

static hf_register_info AFDataReqExtSrsp_msg_info[] =
{
   {
      &AFDataReqExtSrsp_msg_index,
      {
         "AFDataReqExtSrsp",
         "AFDataReqExtSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

extern const value_string StatusType_value_string_table[];
static int AFDataReqExtSrsp_Status_field_index = -1;

static hf_register_info AFDataReqExtSrsp_Status_field_info[] =
{
   {
      &AFDataReqExtSrsp_Status_field_index,
      {
         "Status",
         "AFDataReqExtSrsp.Status",
         FT_UINT8,
         BASE_DEC,
         VALS(StatusType_value_string_table),
         0x0,
         "Status",
         HFILL
      }
   }
};



gint AFDataReqExtSrsp_tree_index = -1;

static gint *AFDataReqExtSrsp_tree_table[] =
{
   &AFDataReqExtSrsp_tree_index
};

void AFDataReqExtSrsp_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSrsp_msg_info,
         array_length(AFDataReqExtSrsp_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataReqExtSrsp_Status_field_info,
         array_length(AFDataReqExtSrsp_Status_field_info)
      );

   proto_register_subtree_array
      (
         AFDataReqExtSrsp_tree_table,
         array_length(AFDataReqExtSrsp_tree_table)
      );
}

guint32 AFDataReqExtSrsp_dissect
   (
      AFDataReqExtSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFDataReqExtSrsp_dissect
      (
         msg,
         NULL,
         AFDataReqExtSrsp_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFDataReqExtSrsp_dissect
   (
      AFDataReqExtSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFDataReqExtSrsp"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFDataReqExtSrsp"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFDataReqExtSrsp_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Status;

      guint8_Status = tvb_get_bits8(tvb, offset, nbit);

      msg->Status = (StatusType) guint8_Status;

      proto_tree_add_uint
         (
            tree,
            AFDataReqExtSrsp_Status_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Status
         );
   }
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint AFDataConfirmAreq_msg_index = -1;

static hf_register_info AFDataConfirmAreq_msg_info[] =
{
   {
      &AFDataConfirmAreq_msg_index,
      {
         "AFDataConfirmAreq",
         "AFDataConfirmAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

extern const value_string StatusType_value_string_table[];
static int AFDataConfirmAreq_Status_field_index = -1;

static hf_register_info AFDataConfirmAreq_Status_field_info[] =
{
   {
      &AFDataConfirmAreq_Status_field_index,
      {
         "Status",
         "AFDataConfirmAreq.Status",
         FT_UINT8,
         BASE_DEC,
         VALS(StatusType_value_string_table),
         0x0,
         "Status",
         HFILL
      }
   }
};


static int AFDataConfirmAreq_EndPoint_field_index = -1;

static hf_register_info AFDataConfirmAreq_EndPoint_field_info[] =
{
   {
      &AFDataConfirmAreq_EndPoint_field_index,
      {
         "EndPoint",
         "AFDataConfirmAreq.EndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "EndPoint",
         HFILL
      }
   }
};


static int AFDataConfirmAreq_TransId_field_index = -1;

static hf_register_info AFDataConfirmAreq_TransId_field_info[] =
{
   {
      &AFDataConfirmAreq_TransId_field_index,
      {
         "TransId",
         "AFDataConfirmAreq.TransId",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "TransId",
         HFILL
      }
   }
};



gint AFDataConfirmAreq_tree_index = -1;

static gint *AFDataConfirmAreq_tree_table[] =
{
   &AFDataConfirmAreq_tree_index
};

void AFDataConfirmAreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFDataConfirmAreq_msg_info,
         array_length(AFDataConfirmAreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataConfirmAreq_Status_field_info,
         array_length(AFDataConfirmAreq_Status_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataConfirmAreq_EndPoint_field_info,
         array_length(AFDataConfirmAreq_EndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFDataConfirmAreq_TransId_field_info,
         array_length(AFDataConfirmAreq_TransId_field_info)
      );

   proto_register_subtree_array
      (
         AFDataConfirmAreq_tree_table,
         array_length(AFDataConfirmAreq_tree_table)
      );
}

guint32 AFDataConfirmAreq_dissect
   (
      AFDataConfirmAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFDataConfirmAreq_dissect
      (
         msg,
         NULL,
         AFDataConfirmAreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFDataConfirmAreq_dissect
   (
      AFDataConfirmAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFDataConfirmAreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFDataConfirmAreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFDataConfirmAreq_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Status;

      guint8_Status = tvb_get_bits8(tvb, offset, nbit);

      msg->Status = (StatusType) guint8_Status;

      proto_tree_add_uint
         (
            tree,
            AFDataConfirmAreq_Status_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Status
         );
   }
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->EndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataConfirmAreq_EndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->EndPoint
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TransId = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFDataConfirmAreq_TransId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TransId
      );
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint AFIncomingMsgAreq_msg_index = -1;

static hf_register_info AFIncomingMsgAreq_msg_info[] =
{
   {
      &AFIncomingMsgAreq_msg_index,
      {
         "AFIncomingMsgAreq",
         "AFIncomingMsgAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int AFIncomingMsgAreq_GroupId_field_index = -1;

static hf_register_info AFIncomingMsgAreq_GroupId_field_info[] =
{
   {
      &AFIncomingMsgAreq_GroupId_field_index,
      {
         "GroupId",
         "AFIncomingMsgAreq.GroupId",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "GroupId",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_ClusterId_field_index = -1;

static hf_register_info AFIncomingMsgAreq_ClusterId_field_info[] =
{
   {
      &AFIncomingMsgAreq_ClusterId_field_index,
      {
         "ClusterId",
         "AFIncomingMsgAreq.ClusterId",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "ClusterId",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_SourceAddress_field_index = -1;

static hf_register_info AFIncomingMsgAreq_SourceAddress_field_info[] =
{
   {
      &AFIncomingMsgAreq_SourceAddress_field_index,
      {
         "SourceAddress",
         "AFIncomingMsgAreq.SourceAddress",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "SourceAddress",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_SourceEndpoint_field_index = -1;

static hf_register_info AFIncomingMsgAreq_SourceEndpoint_field_info[] =
{
   {
      &AFIncomingMsgAreq_SourceEndpoint_field_index,
      {
         "SourceEndpoint",
         "AFIncomingMsgAreq.SourceEndpoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "SourceEndpoint",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_DestnationEndPoint_field_index = -1;

static hf_register_info AFIncomingMsgAreq_DestnationEndPoint_field_info[] =
{
   {
      &AFIncomingMsgAreq_DestnationEndPoint_field_index,
      {
         "DestnationEndPoint",
         "AFIncomingMsgAreq.DestnationEndPoint",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationEndPoint",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_WasBroadcast_field_index = -1;

static hf_register_info AFIncomingMsgAreq_WasBroadcast_field_info[] =
{
   {
      &AFIncomingMsgAreq_WasBroadcast_field_index,
      {
         "WasBroadcast",
         "AFIncomingMsgAreq.WasBroadcast",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "WasBroadcast",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_LinkQuality_field_index = -1;

static hf_register_info AFIncomingMsgAreq_LinkQuality_field_info[] =
{
   {
      &AFIncomingMsgAreq_LinkQuality_field_index,
      {
         "LinkQuality",
         "AFIncomingMsgAreq.LinkQuality",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "LinkQuality",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_SecurityUse_field_index = -1;

static hf_register_info AFIncomingMsgAreq_SecurityUse_field_info[] =
{
   {
      &AFIncomingMsgAreq_SecurityUse_field_index,
      {
         "SecurityUse",
         "AFIncomingMsgAreq.SecurityUse",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "SecurityUse",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_TimeStamp_field_index = -1;

static hf_register_info AFIncomingMsgAreq_TimeStamp_field_info[] =
{
   {
      &AFIncomingMsgAreq_TimeStamp_field_index,
      {
         "TimeStamp",
         "AFIncomingMsgAreq.TimeStamp",
         FT_UINT32,
         BASE_DEC,
         NULL,
         0x0,
         "TimeStamp",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_TransSequenceNumber_field_index = -1;

static hf_register_info AFIncomingMsgAreq_TransSequenceNumber_field_info[] =
{
   {
      &AFIncomingMsgAreq_TransSequenceNumber_field_index,
      {
         "TransSequenceNumber",
         "AFIncomingMsgAreq.TransSequenceNumber",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "TransSequenceNumber",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_Len_field_index = -1;

static hf_register_info AFIncomingMsgAreq_Len_field_info[] =
{
   {
      &AFIncomingMsgAreq_Len_field_index,
      {
         "Len",
         "AFIncomingMsgAreq.Len",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "Len",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_Data_field_index = -1;

static hf_register_info AFIncomingMsgAreq_Data_field_info[] =
{
   {
      &AFIncomingMsgAreq_Data_field_index,
      {
         "Data",
         "AFIncomingMsgAreq.Data",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "Data",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_MacSourceAddress_field_index = -1;

static hf_register_info AFIncomingMsgAreq_MacSourceAddress_field_info[] =
{
   {
      &AFIncomingMsgAreq_MacSourceAddress_field_index,
      {
         "MacSourceAddress",
         "AFIncomingMsgAreq.MacSourceAddress",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "MacSourceAddress",
         HFILL
      }
   }
};


static int AFIncomingMsgAreq_MessageResultRadius_field_index = -1;

static hf_register_info AFIncomingMsgAreq_MessageResultRadius_field_info[] =
{
   {
      &AFIncomingMsgAreq_MessageResultRadius_field_index,
      {
         "MessageResultRadius",
         "AFIncomingMsgAreq.MessageResultRadius",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "MessageResultRadius",
         HFILL
      }
   }
};



gint AFIncomingMsgAreq_tree_index = -1;

static gint *AFIncomingMsgAreq_tree_table[] =
{
   &AFIncomingMsgAreq_tree_index
};

void AFIncomingMsgAreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_msg_info,
         array_length(AFIncomingMsgAreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_GroupId_field_info,
         array_length(AFIncomingMsgAreq_GroupId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_ClusterId_field_info,
         array_length(AFIncomingMsgAreq_ClusterId_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_SourceAddress_field_info,
         array_length(AFIncomingMsgAreq_SourceAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_SourceEndpoint_field_info,
         array_length(AFIncomingMsgAreq_SourceEndpoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_DestnationEndPoint_field_info,
         array_length(AFIncomingMsgAreq_DestnationEndPoint_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_WasBroadcast_field_info,
         array_length(AFIncomingMsgAreq_WasBroadcast_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_LinkQuality_field_info,
         array_length(AFIncomingMsgAreq_LinkQuality_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_SecurityUse_field_info,
         array_length(AFIncomingMsgAreq_SecurityUse_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_TimeStamp_field_info,
         array_length(AFIncomingMsgAreq_TimeStamp_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_TransSequenceNumber_field_info,
         array_length(AFIncomingMsgAreq_TransSequenceNumber_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_Len_field_info,
         array_length(AFIncomingMsgAreq_Len_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_Data_field_info,
         array_length(AFIncomingMsgAreq_Data_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_MacSourceAddress_field_info,
         array_length(AFIncomingMsgAreq_MacSourceAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         AFIncomingMsgAreq_MessageResultRadius_field_info,
         array_length(AFIncomingMsgAreq_MessageResultRadius_field_info)
      );

   proto_register_subtree_array
      (
         AFIncomingMsgAreq_tree_table,
         array_length(AFIncomingMsgAreq_tree_table)
      );
}

guint32 AFIncomingMsgAreq_dissect
   (
      AFIncomingMsgAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _AFIncomingMsgAreq_dissect
      (
         msg,
         NULL,
         AFIncomingMsgAreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _AFIncomingMsgAreq_dissect
   (
      AFIncomingMsgAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "AFIncomingMsgAreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "AFIncomingMsgAreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, AFIncomingMsgAreq_tree_index);
   }
   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->GroupId = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_GroupId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->GroupId
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->ClusterId = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_ClusterId_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->ClusterId
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SourceAddress = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_SourceAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SourceAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SourceEndpoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_SourceEndpoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SourceEndpoint
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationEndPoint = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_DestnationEndPoint_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationEndPoint
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->WasBroadcast = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_WasBroadcast_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->WasBroadcast
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->LinkQuality = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_LinkQuality_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->LinkQuality
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SecurityUse = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_SecurityUse_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SecurityUse
      );
   offset += nbit;

   nbit = 32;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TimeStamp = tvb_get_bits32(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_TimeStamp_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TimeStamp
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TransSequenceNumber = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_TransSequenceNumber_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TransSequenceNumber
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Len = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_Len_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Len
      );
   offset += nbit;

   nbit = ((guint32) ((8) * (msg->Len)));
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   if(nbit != 0)
   {
      nbyte = (nbit + 7) >> 3;
      msg->Data = (guint8 *) wmem_alloc(wmem_packet_scope(), nbyte);
      DISSECTOR_ASSERT(!(msg->Data == NULL));
      memset(msg->Data, 0, nbyte);
      tvb_get_bits_buf_be(tvb, offset, nbit, msg->Data, 0);

      {
         char *text = (char *) wmem_alloc(wmem_packet_scope(), nbyte * 2 + 3);
         char *p = text;
         guint32 j;

         DISSECTOR_ASSERT(text != NULL);
         *p++ = '0';
         *p++ = 'x';
         for(j = 0; j < nbyte; ++j)
         {
            p += sprintf(p, "%02x", msg->Data[j]);
         }
         *p = '\0';

         proto_tree_add_none_format
            (
               tree,
               AFIncomingMsgAreq_Data_field_index,
               tvb,
               offset >> 3,
               ((offset & 0x7) + nbit + 7) >> 3,
               "%s: %s",
               "Data",
               text
            );
      }
      offset += nbit;
   }

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->MacSourceAddress = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_MacSourceAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->MacSourceAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->MessageResultRadius = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         AFIncomingMsgAreq_MessageResultRadius_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->MessageResultRadius
      );
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint ZDOMgmtPermitJoinReqSreq_msg_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSreq_msg_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSreq_msg_index,
      {
         "ZDOMgmtPermitJoinReqSreq",
         "ZDOMgmtPermitJoinReqSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_index,
      {
         "DestnationAddress",
         "ZDOMgmtPermitJoinReqSreq.DestnationAddress",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "DestnationAddress",
         HFILL
      }
   }
};


static int ZDOMgmtPermitJoinReqSreq_Duration_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSreq_Duration_field_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSreq_Duration_field_index,
      {
         "Duration",
         "ZDOMgmtPermitJoinReqSreq.Duration",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "Duration",
         HFILL
      }
   }
};


static int ZDOMgmtPermitJoinReqSreq_TCSignificance_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSreq_TCSignificance_field_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSreq_TCSignificance_field_index,
      {
         "TCSignificance",
         "ZDOMgmtPermitJoinReqSreq.TCSignificance",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "TCSignificance",
         HFILL
      }
   }
};



gint ZDOMgmtPermitJoinReqSreq_tree_index = -1;

static gint *ZDOMgmtPermitJoinReqSreq_tree_table[] =
{
   &ZDOMgmtPermitJoinReqSreq_tree_index
};

void ZDOMgmtPermitJoinReqSreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSreq_msg_info,
         array_length(ZDOMgmtPermitJoinReqSreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_info,
         array_length(ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSreq_Duration_field_info,
         array_length(ZDOMgmtPermitJoinReqSreq_Duration_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSreq_TCSignificance_field_info,
         array_length(ZDOMgmtPermitJoinReqSreq_TCSignificance_field_info)
      );

   proto_register_subtree_array
      (
         ZDOMgmtPermitJoinReqSreq_tree_table,
         array_length(ZDOMgmtPermitJoinReqSreq_tree_table)
      );
}

guint32 ZDOMgmtPermitJoinReqSreq_dissect
   (
      ZDOMgmtPermitJoinReqSreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _ZDOMgmtPermitJoinReqSreq_dissect
      (
         msg,
         NULL,
         ZDOMgmtPermitJoinReqSreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _ZDOMgmtPermitJoinReqSreq_dissect
   (
      ZDOMgmtPermitJoinReqSreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "ZDOMgmtPermitJoinReqSreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "ZDOMgmtPermitJoinReqSreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, ZDOMgmtPermitJoinReqSreq_tree_index);
   }
   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->DestnationAddress = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         ZDOMgmtPermitJoinReqSreq_DestnationAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->DestnationAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->Duration = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         ZDOMgmtPermitJoinReqSreq_Duration_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->Duration
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->TCSignificance = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         ZDOMgmtPermitJoinReqSreq_TCSignificance_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->TCSignificance
      );
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint ZDOMgmtPermitJoinReqSrsp_msg_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSrsp_msg_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSrsp_msg_index,
      {
         "ZDOMgmtPermitJoinReqSrsp",
         "ZDOMgmtPermitJoinReqSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

extern const value_string StatusType_value_string_table[];
static int ZDOMgmtPermitJoinReqSrsp_Status_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinReqSrsp_Status_field_info[] =
{
   {
      &ZDOMgmtPermitJoinReqSrsp_Status_field_index,
      {
         "Status",
         "ZDOMgmtPermitJoinReqSrsp.Status",
         FT_UINT8,
         BASE_DEC,
         VALS(StatusType_value_string_table),
         0x0,
         "Status",
         HFILL
      }
   }
};



gint ZDOMgmtPermitJoinReqSrsp_tree_index = -1;

static gint *ZDOMgmtPermitJoinReqSrsp_tree_table[] =
{
   &ZDOMgmtPermitJoinReqSrsp_tree_index
};

void ZDOMgmtPermitJoinReqSrsp_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSrsp_msg_info,
         array_length(ZDOMgmtPermitJoinReqSrsp_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinReqSrsp_Status_field_info,
         array_length(ZDOMgmtPermitJoinReqSrsp_Status_field_info)
      );

   proto_register_subtree_array
      (
         ZDOMgmtPermitJoinReqSrsp_tree_table,
         array_length(ZDOMgmtPermitJoinReqSrsp_tree_table)
      );
}

guint32 ZDOMgmtPermitJoinReqSrsp_dissect
   (
      ZDOMgmtPermitJoinReqSrsp *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _ZDOMgmtPermitJoinReqSrsp_dissect
      (
         msg,
         NULL,
         ZDOMgmtPermitJoinReqSrsp_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _ZDOMgmtPermitJoinReqSrsp_dissect
   (
      ZDOMgmtPermitJoinReqSrsp *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "ZDOMgmtPermitJoinReqSrsp"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "ZDOMgmtPermitJoinReqSrsp"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, ZDOMgmtPermitJoinReqSrsp_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Status;

      guint8_Status = tvb_get_bits8(tvb, offset, nbit);

      msg->Status = (StatusType) guint8_Status;

      proto_tree_add_uint
         (
            tree,
            ZDOMgmtPermitJoinReqSrsp_Status_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Status
         );
   }
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint ZDOMgmtPermitJoinRspAreq_msg_index = -1;

static hf_register_info ZDOMgmtPermitJoinRspAreq_msg_info[] =
{
   {
      &ZDOMgmtPermitJoinRspAreq_msg_index,
      {
         "ZDOMgmtPermitJoinRspAreq",
         "ZDOMgmtPermitJoinRspAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int ZDOMgmtPermitJoinRspAreq_SourceAddress_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinRspAreq_SourceAddress_field_info[] =
{
   {
      &ZDOMgmtPermitJoinRspAreq_SourceAddress_field_index,
      {
         "SourceAddress",
         "ZDOMgmtPermitJoinRspAreq.SourceAddress",
         FT_UINT16,
         BASE_DEC,
         NULL,
         0x0,
         "SourceAddress",
         HFILL
      }
   }
};


extern const value_string StatusType_value_string_table[];
static int ZDOMgmtPermitJoinRspAreq_Status_field_index = -1;

static hf_register_info ZDOMgmtPermitJoinRspAreq_Status_field_info[] =
{
   {
      &ZDOMgmtPermitJoinRspAreq_Status_field_index,
      {
         "Status",
         "ZDOMgmtPermitJoinRspAreq.Status",
         FT_UINT8,
         BASE_DEC,
         VALS(StatusType_value_string_table),
         0x0,
         "Status",
         HFILL
      }
   }
};



gint ZDOMgmtPermitJoinRspAreq_tree_index = -1;

static gint *ZDOMgmtPermitJoinRspAreq_tree_table[] =
{
   &ZDOMgmtPermitJoinRspAreq_tree_index
};

void ZDOMgmtPermitJoinRspAreq_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinRspAreq_msg_info,
         array_length(ZDOMgmtPermitJoinRspAreq_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinRspAreq_SourceAddress_field_info,
         array_length(ZDOMgmtPermitJoinRspAreq_SourceAddress_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZDOMgmtPermitJoinRspAreq_Status_field_info,
         array_length(ZDOMgmtPermitJoinRspAreq_Status_field_info)
      );

   proto_register_subtree_array
      (
         ZDOMgmtPermitJoinRspAreq_tree_table,
         array_length(ZDOMgmtPermitJoinRspAreq_tree_table)
      );
}

guint32 ZDOMgmtPermitJoinRspAreq_dissect
   (
      ZDOMgmtPermitJoinRspAreq *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _ZDOMgmtPermitJoinRspAreq_dissect
      (
         msg,
         NULL,
         ZDOMgmtPermitJoinRspAreq_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _ZDOMgmtPermitJoinRspAreq_dissect
   (
      ZDOMgmtPermitJoinRspAreq *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "ZDOMgmtPermitJoinRspAreq"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "ZDOMgmtPermitJoinRspAreq"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, ZDOMgmtPermitJoinRspAreq_tree_index);
   }
   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->SourceAddress = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

   proto_tree_add_uint
      (
         tree,
         ZDOMgmtPermitJoinRspAreq_SourceAddress_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->SourceAddress
      );
   offset += nbit;

   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint8 guint8_Status;

      guint8_Status = tvb_get_bits8(tvb, offset, nbit);

      msg->Status = (StatusType) guint8_Status;

      proto_tree_add_uint
         (
            tree,
            ZDOMgmtPermitJoinRspAreq_Status_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint8_Status
         );
   }
   offset += nbit;

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

gint ZnpPacket_msg_index = -1;

static hf_register_info ZnpPacket_msg_info[] =
{
   {
      &ZnpPacket_msg_index,
      {
         "ZnpPacket",
         "ZnpPacket",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         NULL,
         HFILL
      }
   }
};

static int ZnpPacket_StartBytes_field_index = -1;

static hf_register_info ZnpPacket_StartBytes_field_info[] =
{
   {
      &ZnpPacket_StartBytes_field_index,
      {
         "StartBytes",
         "ZnpPacket.StartBytes",
         FT_UINT8,
         BASE_DEC,
         NULL,
         0x0,
         "StartBytes",
         HFILL
      }
   }
};


extern const value_string ZnpCpmmandType_value_string_table[];
static int ZnpPacket_CmdType_field_index = -1;

static hf_register_info ZnpPacket_CmdType_field_info[] =
{
   {
      &ZnpPacket_CmdType_field_index,
      {
         "CmdType",
         "ZnpPacket.CmdType",
         FT_UINT16,
         BASE_DEC,
         VALS(ZnpCpmmandType_value_string_table),
         0x0,
         "CmdType",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_afDataReqSreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_afDataReqSreq_field_info[] =
{
   {
      &ZnpPacket_Payload_afDataReqSreq_field_index,
      {
         "afDataReqSreq",
         "ZnpPacket.afDataReqSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "afDataReqSreq",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_afDataReqSrsp_field_index = -1;

static hf_register_info ZnpPacket_Payload_afDataReqSrsp_field_info[] =
{
   {
      &ZnpPacket_Payload_afDataReqSrsp_field_index,
      {
         "afDataReqSrsp",
         "ZnpPacket.afDataReqSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "afDataReqSrsp",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_afDataReqExtSreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_afDataReqExtSreq_field_info[] =
{
   {
      &ZnpPacket_Payload_afDataReqExtSreq_field_index,
      {
         "afDataReqExtSreq",
         "ZnpPacket.afDataReqExtSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "afDataReqExtSreq",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_afDataReqExtSrsp_field_index = -1;

static hf_register_info ZnpPacket_Payload_afDataReqExtSrsp_field_info[] =
{
   {
      &ZnpPacket_Payload_afDataReqExtSrsp_field_index,
      {
         "afDataReqExtSrsp",
         "ZnpPacket.afDataReqExtSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "afDataReqExtSrsp",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_adDataConfirmAreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_adDataConfirmAreq_field_info[] =
{
   {
      &ZnpPacket_Payload_adDataConfirmAreq_field_index,
      {
         "adDataConfirmAreq",
         "ZnpPacket.adDataConfirmAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "adDataConfirmAreq",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_afIncomingMsgAreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_afIncomingMsgAreq_field_info[] =
{
   {
      &ZnpPacket_Payload_afIncomingMsgAreq_field_index,
      {
         "afIncomingMsgAreq",
         "ZnpPacket.afIncomingMsgAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "afIncomingMsgAreq",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_info[] =
{
   {
      &ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_index,
      {
         "zdoMgmtPermitJoinReqSreq",
         "ZnpPacket.zdoMgmtPermitJoinReqSreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "zdoMgmtPermitJoinReqSreq",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_index = -1;

static hf_register_info ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_info[] =
{
   {
      &ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_index,
      {
         "zdoMgmtPermitJoinReqSrsp",
         "ZnpPacket.zdoMgmtPermitJoinReqSrsp",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "zdoMgmtPermitJoinReqSrsp",
         HFILL
      }
   }
};


static int ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_index = -1;

static hf_register_info ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_info[] =
{
   {
      &ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_index,
      {
         "zdoMgmtPermitJoinRspAreq",
         "ZnpPacket.zdoMgmtPermitJoinRspAreq",
         FT_NONE,
         BASE_NONE,
         NULL,
         0x0,
         "zdoMgmtPermitJoinRspAreq",
         HFILL
      }
   }
};




gint ZnpPacket_tree_index = -1;

static gint *ZnpPacket_tree_table[] =
{
   &ZnpPacket_tree_index
};

void ZnpPacket_register(int proto_index)
{
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_msg_info,
         array_length(ZnpPacket_msg_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZnpPacket_StartBytes_field_info,
         array_length(ZnpPacket_StartBytes_field_info)
      );

   proto_register_field_array
      (
         proto_index,
         ZnpPacket_CmdType_field_info,
         array_length(ZnpPacket_CmdType_field_info)
      );

   {
      extern void AFDataReqSreq_register(int);
      extern int AFDataReqSreq_tree_index;

      if(AFDataReqSreq_tree_index == -1)
      {
         AFDataReqSreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_afDataReqSreq_field_info,
         array_length(ZnpPacket_Payload_afDataReqSreq_field_info)
      );

   {
      extern void AFDataReqSrsp_register(int);
      extern int AFDataReqSrsp_tree_index;

      if(AFDataReqSrsp_tree_index == -1)
      {
         AFDataReqSrsp_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_afDataReqSrsp_field_info,
         array_length(ZnpPacket_Payload_afDataReqSrsp_field_info)
      );

   {
      extern void AFDataReqExtSreq_register(int);
      extern int AFDataReqExtSreq_tree_index;

      if(AFDataReqExtSreq_tree_index == -1)
      {
         AFDataReqExtSreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_afDataReqExtSreq_field_info,
         array_length(ZnpPacket_Payload_afDataReqExtSreq_field_info)
      );

   {
      extern void AFDataReqExtSrsp_register(int);
      extern int AFDataReqExtSrsp_tree_index;

      if(AFDataReqExtSrsp_tree_index == -1)
      {
         AFDataReqExtSrsp_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_afDataReqExtSrsp_field_info,
         array_length(ZnpPacket_Payload_afDataReqExtSrsp_field_info)
      );

   {
      extern void AFDataConfirmAreq_register(int);
      extern int AFDataConfirmAreq_tree_index;

      if(AFDataConfirmAreq_tree_index == -1)
      {
         AFDataConfirmAreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_adDataConfirmAreq_field_info,
         array_length(ZnpPacket_Payload_adDataConfirmAreq_field_info)
      );

   {
      extern void AFIncomingMsgAreq_register(int);
      extern int AFIncomingMsgAreq_tree_index;

      if(AFIncomingMsgAreq_tree_index == -1)
      {
         AFIncomingMsgAreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_afIncomingMsgAreq_field_info,
         array_length(ZnpPacket_Payload_afIncomingMsgAreq_field_info)
      );

   {
      extern void ZDOMgmtPermitJoinReqSreq_register(int);
      extern int ZDOMgmtPermitJoinReqSreq_tree_index;

      if(ZDOMgmtPermitJoinReqSreq_tree_index == -1)
      {
         ZDOMgmtPermitJoinReqSreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_info,
         array_length(ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_info)
      );

   {
      extern void ZDOMgmtPermitJoinReqSrsp_register(int);
      extern int ZDOMgmtPermitJoinReqSrsp_tree_index;

      if(ZDOMgmtPermitJoinReqSrsp_tree_index == -1)
      {
         ZDOMgmtPermitJoinReqSrsp_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_info,
         array_length(ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_info)
      );

   {
      extern void ZDOMgmtPermitJoinRspAreq_register(int);
      extern int ZDOMgmtPermitJoinRspAreq_tree_index;

      if(ZDOMgmtPermitJoinRspAreq_tree_index == -1)
      {
         ZDOMgmtPermitJoinRspAreq_register(proto_index);
      }
   }
   proto_register_field_array
      (
         proto_index,
         ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_info,
         array_length(ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_info)
      );


   proto_register_subtree_array
      (
         ZnpPacket_tree_table,
         array_length(ZnpPacket_tree_table)
      );
}

guint32 ZnpPacket_dissect
   (
      ZnpPacket *msg,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   return _ZnpPacket_dissect
      (
         msg,
         NULL,
         ZnpPacket_msg_index,
         proto_index,
         tvb,
         offset,
         (tvb_captured_length_remaining(tvb, offset >> 3) << 3) - (offset & 0x7),
         pinfo,
         tree
      );
}

guint32 _ZnpPacket_dissect
   (
      ZnpPacket *msg,
      const char  *field_name,
      int          field_index,
      int          proto_index,
      tvbuff_t    *tvb,
      guint32      offset,
      guint32      length,
      packet_info *pinfo,
      proto_tree  *tree
   )
{
   char    msg_field_name[MAX_TSN1_MSG_FIELD_NAME_LEN];
   guint32 soffset = offset;
   guint32 eoffset = offset + length;
   guint32 nbit;
   guint32 nbyte;
   proto_item *ti;

   /* Disable unused variable warnings */
   (void) msg;
   (void) field_name;
   (void) field_index;
   (void) proto_index;
   (void) tvb;
   (void) pinfo;
   (void) msg_field_name;
   (void) eoffset;
   (void) nbit;
   (void) nbyte;

   if(field_name != NULL)
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s: %s",
            field_name,
            "ZnpPacket"
         );
   }
   else
   {
      ti = proto_tree_add_none_format
         (
            tree,
            field_index,
            tvb, offset >> 3, 0,
            "%s",
            "ZnpPacket"
         );
   }

   if(ti != NULL)
   {
      tree = proto_item_add_subtree(ti, ZnpPacket_tree_index);
   }
   nbit = 8;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   msg->StartBytes = tvb_get_bits8(tvb, offset, nbit);

   proto_tree_add_uint
      (
         tree,
         ZnpPacket_StartBytes_field_index,
         tvb,
         offset >> 3,
         ((offset & 0x7) + nbit + 7) >> 3,
         msg->StartBytes
      );
   offset += nbit;

   nbit = 16;
   DISSECTOR_ASSERT(!(nbit > eoffset - offset));
   {
      guint16 guint16_CmdType;

      guint16_CmdType = tvb_get_bits16(tvb, offset, nbit, ENC_BIG_ENDIAN);

      msg->CmdType = (ZnpCpmmandType) guint16_CmdType;

      proto_tree_add_uint
         (
            tree,
            ZnpPacket_CmdType_field_index,
            tvb,
            offset >> 3,
            ((offset & 0x7) + nbit + 7) >> 3,
            guint16_CmdType
         );
   }
   offset += nbit;

   switch(((guint16) msg->CmdType))
   {
    case 9217:
      msg->Payload.afDataReqSreq = (AFDataReqSreq *) wmem_alloc(wmem_packet_scope(), sizeof(AFDataReqSreq));
      DISSECTOR_ASSERT(!(msg->Payload.afDataReqSreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "afDataReqSreq");
      nbit = _AFDataReqSreq_dissect
         (
            msg->Payload.afDataReqSreq,
            msg_field_name,
            ZnpPacket_Payload_afDataReqSreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 25601:
      msg->Payload.afDataReqSrsp = (AFDataReqSrsp *) wmem_alloc(wmem_packet_scope(), sizeof(AFDataReqSrsp));
      DISSECTOR_ASSERT(!(msg->Payload.afDataReqSrsp == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "afDataReqSrsp");
      nbit = _AFDataReqSrsp_dissect
         (
            msg->Payload.afDataReqSrsp,
            msg_field_name,
            ZnpPacket_Payload_afDataReqSrsp_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 9218:
      msg->Payload.afDataReqExtSreq = (AFDataReqExtSreq *) wmem_alloc(wmem_packet_scope(), sizeof(AFDataReqExtSreq));
      DISSECTOR_ASSERT(!(msg->Payload.afDataReqExtSreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "afDataReqExtSreq");
      nbit = _AFDataReqExtSreq_dissect
         (
            msg->Payload.afDataReqExtSreq,
            msg_field_name,
            ZnpPacket_Payload_afDataReqExtSreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 25602:
      msg->Payload.afDataReqExtSrsp = (AFDataReqExtSrsp *) wmem_alloc(wmem_packet_scope(), sizeof(AFDataReqExtSrsp));
      DISSECTOR_ASSERT(!(msg->Payload.afDataReqExtSrsp == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "afDataReqExtSrsp");
      nbit = _AFDataReqExtSrsp_dissect
         (
            msg->Payload.afDataReqExtSrsp,
            msg_field_name,
            ZnpPacket_Payload_afDataReqExtSrsp_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 17536:
      msg->Payload.adDataConfirmAreq = (AFDataConfirmAreq *) wmem_alloc(wmem_packet_scope(), sizeof(AFDataConfirmAreq));
      DISSECTOR_ASSERT(!(msg->Payload.adDataConfirmAreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "adDataConfirmAreq");
      nbit = _AFDataConfirmAreq_dissect
         (
            msg->Payload.adDataConfirmAreq,
            msg_field_name,
            ZnpPacket_Payload_adDataConfirmAreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 17537:
      msg->Payload.afIncomingMsgAreq = (AFIncomingMsgAreq *) wmem_alloc(wmem_packet_scope(), sizeof(AFIncomingMsgAreq));
      DISSECTOR_ASSERT(!(msg->Payload.afIncomingMsgAreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "afIncomingMsgAreq");
      nbit = _AFIncomingMsgAreq_dissect
         (
            msg->Payload.afIncomingMsgAreq,
            msg_field_name,
            ZnpPacket_Payload_afIncomingMsgAreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 9526:
      msg->Payload.zdoMgmtPermitJoinReqSreq = (ZDOMgmtPermitJoinReqSreq *) wmem_alloc(wmem_packet_scope(), sizeof(ZDOMgmtPermitJoinReqSreq));
      DISSECTOR_ASSERT(!(msg->Payload.zdoMgmtPermitJoinReqSreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "zdoMgmtPermitJoinReqSreq");
      nbit = _ZDOMgmtPermitJoinReqSreq_dissect
         (
            msg->Payload.zdoMgmtPermitJoinReqSreq,
            msg_field_name,
            ZnpPacket_Payload_zdoMgmtPermitJoinReqSreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 25910:
      msg->Payload.zdoMgmtPermitJoinReqSrsp = (ZDOMgmtPermitJoinReqSrsp *) wmem_alloc(wmem_packet_scope(), sizeof(ZDOMgmtPermitJoinReqSrsp));
      DISSECTOR_ASSERT(!(msg->Payload.zdoMgmtPermitJoinReqSrsp == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "zdoMgmtPermitJoinReqSrsp");
      nbit = _ZDOMgmtPermitJoinReqSrsp_dissect
         (
            msg->Payload.zdoMgmtPermitJoinReqSrsp,
            msg_field_name,
            ZnpPacket_Payload_zdoMgmtPermitJoinReqSrsp_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    case 17846:
      msg->Payload.zdoMgmtPermitJoinRspAreq = (ZDOMgmtPermitJoinRspAreq *) wmem_alloc(wmem_packet_scope(), sizeof(ZDOMgmtPermitJoinRspAreq));
      DISSECTOR_ASSERT(!(msg->Payload.zdoMgmtPermitJoinRspAreq == NULL));

      snprintf(msg_field_name, sizeof(msg_field_name), "zdoMgmtPermitJoinRspAreq");
      nbit = _ZDOMgmtPermitJoinRspAreq_dissect
         (
            msg->Payload.zdoMgmtPermitJoinRspAreq,
            msg_field_name,
            ZnpPacket_Payload_zdoMgmtPermitJoinRspAreq_field_index,
            proto_index,
            tvb,
            offset,
            eoffset - offset,
            pinfo,
            tree
         );
      offset += nbit;
      break;

    default:
      break;
   }

   ti = proto_tree_get_parent(tree);
   proto_item_set_len(ti, (offset - soffset + 7) >> 3);

   return offset - soffset;
}

